### ISSUE TITLE
实现无关的 metrics

### ISSUE THREAD

**Issue by exfly** [go-gorm/prometheus#6]
## Describe the feature

[prometheus golang mysql](https://github.com/go-gorm/prometheus/blob/master/mysql.go#L89) 实现看到只用到了 gauge，是否可以提供更实现无关的 metrics 支持呢？比如我们已经在使用的 [metrics wrapper](https://github.com/jaegertracing/jaeger-lib/blob/master/metrics/gauge.go),几乎无法使用 go-gorm/prometheus 此项目。

当然这样此项目会更名为 go-gorm/metrics 会比较好一些

**Comment by uxgnaw** [comment]
关于更多metrics的支持，可以详细的说明一下吗？

**Comment by exfly** [comment]
更多 metrics 支持是指：
1. go-kit 的 metrics interface
2. 直接裸用 prometheus interface使用 metrics
3. 直接使用 [jaeger-lib/metrics](https://github.com/jaegertracing/jaeger-lib/blob/master/metrics/gauge.go)

等等 metrics 的实际使用场景

**Comment by uxgnaw** [comment]
我理解你的问题是不能用gorm prometheus和其他类库的metrics一起使用（比如go kit），我写了个测试，发现一起使用没问题。你看看是否满足你的需求
`package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	kitprometheus "github.com/go-kit/kit/metrics/prometheus"
	"github.com/gorilla/mux"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/plugin/prometheus"
)

func main() {
	db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{})
	if err != nil {
		log.Panic(err)
	}

	db.Use(prometheus.New(prometheus.Config{
		DBName:          "db1", // `DBName` as metrics label
		RefreshInterval: 15,    // refresh metrics interval (default 15 seconds)
		StartServer:     false,  // start http server to expose metrics
		HTTPServerPort:  8080,  // configure http server port, default port 8080 (if you have configured multiple instances, only the first `HTTPServerPort` will be used to start server)
	}))

	address := fmt.Sprintf("%s:%d", "0.0.0.0", 8080)
	router := mux.NewRouter().StrictSlash(true)

	router.Handle("/metrics", promhttp.Handler())
	go func() {
		err := http.ListenAndServe(address, router)
		if err != nil {
			log.Panic("ListenAndServe err:", err)
		}
	}()

	counter := kitprometheus.NewCounterFrom(
		stdprometheus.CounterOpts{
			Namespace: "mynamespace",
			Name:      "myname",
			Help:      "Sample of Counter metrics",
		},
		[]string{"type", "group"})

	for {
		counter.With("type", "mytype", "group", "mygroup").Add(10)
		time.Sleep(5 * time.Second)
	}
}
`
